//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("CatenaLogic")]
[assembly: AssemblyVersion("4.5.0")]
[assembly: AssemblyFileVersion("4.5.0")]
[assembly: AssemblyInformationalVersion("4.5.0-alpha.171")]
[assembly: AssemblyCopyright("Copyright © CatenaLogic 2010 - 2020")]

