//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("CatenaLogic")]
[assembly: AssemblyVersion("4.4.1")]
[assembly: AssemblyFileVersion("4.4.1")]
[assembly: AssemblyInformationalVersion("4.4.1-beta.1+157")]
[assembly: AssemblyCopyright("Copyright © CatenaLogic 2010 - 2020")]

